#!/usr/bin/env bash

directories=(~/repo ~/.config ~/.local/bin)

for dir in "${directories[@]}"; do
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

cur_dir=$(pwd)
repo_dir=~/repo
cd "$repo_dir" || exit

git clone git@github.com:whonathan/dotfiles.git

paths=(
    ".config/alacritty"
    ".config/fish"
    ".config/nvim"
    ".config/hypr"
    ".config/waybar"
    ".config/starship.toml"
    ".local/bin/encrypt"
    ".local/bin/decrypt"
    ".local/bin/packer"
    ".local/bin/udf"
)

for path in "${paths[@]}"; do
    full_path=~/"$path"
    if [ -e "$full_path" ]; then
        if [ -d "$full_path" ]; then
            rm -fr "$full_path"
        elif [ -f "$full_path" ]; then
            rm -f "$full_path"
        fi
    fi
    ln -fs "$repo_dir"/dotfiles/"$path" "$full_path"
done

echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc

cd "$cur_dir"
